In [1]:
import tensorflow as tf 
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\Aarin Zacharia\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


Tensors

In [3]:
string = tf.Variable("this is string" ,tf.string)
number = tf.Variable(123, tf.int16)
float_num = tf.Variable(12.34, tf.float64)

#scalar tensors / rank 0

In [4]:
rank1_tensor = tf.Variable(["123", "hello", "yes"], tf.string)
rank2_tensor = tf.Variable([["4567", "ok"], ["no", "yes"]], tf.string)



In [7]:
tf.rank(rank2_tensor)
#determines rank

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Shape of Tensors
-tells us the amount of elem that are present in each dimension

In [8]:
rank2_tensor.shape

TensorShape([2, 2])

In [9]:
rank1_tensor.shape

TensorShape([3])

Changing of shape

In [13]:
tens1 = tf.ones([1,2,3]) #ones - 1 exterior list, 2 list inside of it, 3 elems in those 2 list
tens2 = tf.reshape(tens1, [2,3,1])

In [14]:
print(tens1)
print(tens2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [24]:
t1 = tf.zeros([1,2,4,5])
print(t1)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(1, 2, 4, 5), dtype=float32)


Slicing Tensors

In [15]:
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [16]:
three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  

tf.Tensor(3, shape=(), dtype=int32)


In [17]:
row1 = tensor[0] 
print(row1)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [18]:
column1 = tensor[:, 0]  # selects the first column
print(column1)

tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)


In [20]:
row2and4 = tensor[1::2]  # selects second and fourth row
print(row2and4)

tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
